spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql 8.0
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  # 配置mapper xml文件所在路径
  mapper-locations: classpath:mappers/*.xml
  # 配置映射类所在包名
  type-aliases-package: com.example.mybatis.entity
  configuration:
    use-generated-keys: true

logging:
  level:
    com.example.mybatis.mapper: debug